name: Run Tests

# - run tests

on:
  push:
    branches: master

jobs:
  build:
    environment: tests-and-code-coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci
    - run: npm run test:coverage:report
      env:
        RABBIT_URL: ${{ secrets.RABBITMQ_URL }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}